### ISSUE TITLE
Deployment fail

### ISSUE THREAD

**Issue by sondoha** [REBELinBLUE/deployer#329]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Deploy my WordPress website

### Actual behaviour

I got this error when trying to test deployment.

![image](https://cloud.githubusercontent.com/assets/5657882/23590836/d0146fac-0219-11e7-9f3c-6c54b1dc02b3.png)

and here is error message when I access that deployment history:

```php
BadMethodCallException in Builder.php line 2508:
Call to undefined method Illuminate\Database\Query\Builder::getPresenter()
```

### Steps to reproduce

After setup deployment commands. Run "Deployment"

### Laravel Environment

- Laravel Version: 5.4.15 
 - Timezone: Asia/Ho_Chi_Minh 
 - Debug Mode: ✔ 
 - Storage Dir Writable: ✔ 
 - Cache Dir Writable: ✔ 
 - Decomposer Version: ^1.0 
 - App Size: 44 MB

 ### Server Environment

 - PHP Version: 7.0.16
 - Server Software: Apache/2.4.25 (Unix) OpenSSL/1.0.2g
 - Server OS: Linux va-dev 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64
 - Database: mysql
 - SSL Installed: ✘
 - Cache Driver: file
 - Session Driver: file
 - Openssl Ext: ✔
 - PDO Ext: ✔
 - Mbstring Ext: ✔
 - Tokenizer Ext: ✔
 - XML Ext: ✔

 ### Installed Packages & their version numbers
 - andywer/js-localization : dev-laravel-5
 - backup-manager/laravel : ^1.1
 - creativeorange/gravatar : ~1.0
 - cweagans/composer-patches : ^1.6
 - doctrine/dbal : ~2.5
 - fideloper/proxy : ^3.1
 - graham-campbell/binput : ~3.3
 - graham-campbell/htmlmin : ~4.2
 - guzzlehttp/guzzle : ^6.2
 - intervention/image : ^2.3
 - laravel-notification-channels/hipchat : ~0.2
 - laravel-notification-channels/twilio : ~1.0.2
 - laravel-notification-channels/webhook : ~1.0.2
 - laravel/framework : ^5.4
 - laravel/tinker : 1.0.*
 - lubusin/laravel-decomposer : ^1.0
 - mccool/laravel-auto-presenter : ^5.0
 - michele-angioni/multi-language : 0.3
 - pda/pheanstalk : ~3.1
 - pragmarx/google2fa : ^1.0.0
 - predis/predis : ~1.0
 - tymon/jwt-auth : ~0.5
 - version/version : ^2.2

### Logs (see storage/logs/) or other output that would be helpful

https://gist.github.com/sondoha/61dbc13230520f8310d7795250c4089a

Can you please advice? Thank you!

**Comment by REBELinBLUE** [comment]
Looks like the `master` branch is broken, I will investigate. Can you switch to the `0.0.44` tag?

**Comment by REBELinBLUE** [comment]
OK found the problem, fixing now

**Comment by REBELinBLUE** [comment]
Fixed, sorry about that

**Comment by sondoha** [comment]
Awesome! Thank you very much. 

I can access deployment history now but the deployment status is still failed.

![image](https://cloud.githubusercontent.com/assets/5657882/23594827/b10d738e-024f-11e7-82f8-d7e5d700d06d.png)

I'm not sure if I configure deployment commands correctly, can you please show a an example about it?
Currently, I put something like this in all commands:

```shell
echo 'OK' > test.txt
```

To test if it work but I think I did it wrong.

**Comment by REBELinBLUE** [comment]
Sorry I should have said, you'll need to run `php artisan queue:restart` after pulling, or `php artisan app:update`. To restart the queue listener

**Comment by sondoha** [comment]
Thank you! I have followed your instruction 
![image](https://cloud.githubusercontent.com/assets/5657882/23628629/8081e464-02e7-11e7-8039-54edfabffaec.png)

but it did not work. Here is current status:

![image](https://cloud.githubusercontent.com/assets/5657882/23628283/6758152c-02e6-11e7-8156-2ef84961299f.png)

And here are the files on staging server so far:
![image](https://cloud.githubusercontent.com/assets/5657882/23628601/60436538-02e7-11e7-8f76-7b8909426ad5.png)

Do you know why?

**Comment by REBELinBLUE** [comment]
Hmm, this is odd. Can you paste the new log?

**Comment by sondoha** [comment]
Here you go:
https://gist.github.com/sondoha/04fc82a1b1d8d9683253cda94a305645

**Comment by hellojing** [comment]
We have the same problem,test is ok,but deployment is failed.

**Comment by REBELinBLUE** [comment]
@sondoha hmm, this is weird, the log says it is on line 128 on DeploymentController

```
#2 /srv/users/serverpilot/apps/deployer/app/Http/Controllers/DeploymentController.php(128): Illuminate\Database\Eloquent\Model->__call('getPresenter', Array)
```

which is where it use to be but it definitely isn't now https://github.com/REBELinBLUE/deployer/blob/master/app/Http/Controllers/DeploymentController.php#L124-L132

Can you confirm yours matches?

One other idea, can you try restarting php-fpm?


@hellojing Can you provide the log please?

**Comment by sondoha** [comment]
Hi, I have removed that log file and restarted php. But I don't get any new log.

**Comment by sondoha** [comment]
I have deployed WordPress website, it did not contain composer in the root folder. Is that something causing the error?

**Comment by REBELinBLUE** [comment]
Can you show me what `$ git status -uno` gives?

It should work fine without a composer.json file, the composer step checks if the file exists first; and we used it on wordpress sites at my previous job

**Comment by sondoha** [comment]
Here it is:

![image](https://cloud.githubusercontent.com/assets/5657882/23668917/25b9b97c-0395-11e7-884a-9a70788f7204.png)

**Comment by REBELinBLUE** [comment]
Hmm, can you switch to tag 0.0.44 and see if that works?

**Comment by sondoha** [comment]
Thank you! I will inform you soon. And I am using php 7.0. Is that a problem with php version?

**Comment by REBELinBLUE** [comment]
Shouldn't be, I am using PHP 7.0

**Comment by sondoha** [comment]
I switched to tag 0.0.44 and got this error:
```
Interface 'Robbo\Presenter\PresentableInterface' not found
```

Am I missing something?

**Comment by REBELinBLUE** [comment]
Need to run `composer install --production` and `php artisan app:update` when switching version ;)

**Comment by sondoha** [comment]
do you mean `composer install` and `npm install --production` and `php artisan app:update`?

**Comment by REBELinBLUE** [comment]
Yeah sorry that is what i meant

**Comment by sondoha** [comment]
I'm sorry but still no luck. I will try to re-install the application on another server an let you know later. Thank you for your time! 👍

**Comment by REBELinBLUE** [comment]
Really odd. Do you have anything like APC or opcache installed?

**Comment by sondoha** [comment]
I moved the deployer application to another server today. Still got the same issue. I don't have APC.

Is there any important configuration for nginx?

**Comment by REBELinBLUE** [comment]
hmm, no. When you say you moved it do you mean you installed a new copy or you moved the files? It really seems like there is something messed up in your copy because `getPresenter` does not exist anywhere in the code anymore :|

**Comment by dgpro** [comment]
I've got the same problem as @sondoha after upgrading to version 0.0.44 on Ubuntu 16.04, Nginx 1.11.10, PHP 7.0.
This is redis status::
```
$ service redis-server status
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-03-15 17:29:08 GMT; 13min ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 4208 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=0/SUCCESS)
  Process: 4203 ExecStop=/bin/kill -s TERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 4198 ExecStop=/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d (code=exited, status=0/SUCCESS)
  Process: 4225 ExecStartPost=/bin/run-parts --verbose /etc/redis/redis-server.post-up.d (code=exited, status=0/SUCCESS)
  Process: 4221 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=0/SUCCESS)
  Process: 4216 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=0/SUCCESS)
 Main PID: 4224 (redis-server)
   CGroup: /system.slice/redis-server.service
           └─4224 /usr/bin/redis-server 127.0.0.1:6379
```
Redis process:
```
$ ps aux | grep redis
redis     4224  0.1  0.8  36408  8188 ?        Ssl  17:29   0:00 /usr/bin/redis-server 127.0.0.1:6379
```
Supervisor status:
```
$ service supervisor status
● supervisor.service - Supervisor process control system for UNIX
   Loaded: loaded (/lib/systemd/system/supervisor.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-03-15 16:49:33 GMT; 54min ago
     Docs: http://supervisord.org
  Process: 2924 ExecStop=/usr/bin/supervisorctl $OPTIONS shutdown (code=exited, status=0/SUCCESS)
 Main PID: 2930 (supervisord)
   CGroup: /system.slice/supervisor.service
           ├─2930 /usr/bin/python /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
           ├─2941 php /var/www/phpci/console phpci:worker
           ├─2942 php /var/www/phpci/console phpci:worker
           ├─4892 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
           ├─4900 php artisan queue:work --queue=deployer-default --sleep=3 --tries=1 --daemon
           ├─4907 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
           ├─4914 node socket.js
           └─4920 php artisan queue:work --queue=deployer-high,deployer-low --sleep=3 --tries=1 --daemon
```
Some info in [deployer-socket-stdout.log](https://gist.github.com/dgpro/a512d870fb536d244c078219356f0e1a)
Laravel log is empty
It was working before the upgrade but now just hangs on "Create New Release" and fails, not sure what to look at.

**Comment by dgpro** [comment]
I wish I found you [answer](https://github.com/REBELinBLUE/deployer/issues/327#issuecomment-284333461) earlier @REBELinBLUE!
This worked for me:
```
echo 'BEANSTALKD_EXTRA="-z 524280"' >> /etc/default/beanstalkd
sudo service beanstalkd restart
```
Thanks a lot

**Comment by REBELinBLUE** [comment]
Sorry I didn't see your response yesterday. I have fixed this in master and plan to release a new tag at the weekly.

Ironically it has only started happening because part of the event broadcasting wasn't working correctly before so log changes were not being broadcast so I fixed that and now that has resulted in the error because the log gets too big for beanstalkd

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by sondoha** [comment]
@REBELinBLUE  Hey Stephen, great to hear that the issue has been fixed. I just need to get latest code for the fixes? Or I will need to do something with beanstalkd?

**Comment by REBELinBLUE** [comment]
@sondoha Sorry that was to @dgpro 

I still haven't figured out your issue, mainly because I can't find anywhere that interface is used because it has been removed.

Could you try removing `bootstrap/cache/*.php` and run `php artisan optimize` ?

**Comment by REBELinBLUE** [comment]
any luck?

**Comment by sondoha** [comment]
I'm sorry. I was busy these days. I will try again soon and let you know. Thank you!

**Comment by REBELinBLUE** [comment]
I'll close this for now, feel free to reopen
