### ISSUE TITLE
Failure log

### ISSUE THREAD

**Issue by cfpinto** [REBELinBLUE/deployer#330]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/REBElinBLUE/deployer/releases/latest) version of Deployer.
- [x] Ensure that you're running at least PHP 5.6.4, you can check this by running `php -v`
- [x] You've ran `composer install --no-dev` from the root of your installation.
- [x] You've ran `npm install --production` from the root of your installation.
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your installation.
- [x] You have restarted the queue listener and node socket server.

To help us better understand your issue, please answer the following.

### Expected behaviour

Log errors on failure

### Actual behaviour

Nothing present on logs as to reason of failure

### Steps to reproduce

When a new deployment is started it always fails on create new release step. There is no information about the error both on the logs and output. The only info is present in the process output and says "Process Output (Create New Release)"

### Environment info

Visit /admin/sysinfo on your install and click the "Get System Report" button. Paste the report here, if you can't
please provide the following instead.

Operating System: Ubuntu Server 16.04.2 LTS
PHP Version: 7.0
Node Version: 6.9
Database System: MySql 
Database Version: 5.7.17

### Logs (see storage/logs/) or other output that would be helpful
nothing on the logs

The way a deployment is setup is a bit unclear I must be doing something wrong but I can't find any logs that could help me.

Please help

Cheers
Claudio

**Comment by REBELinBLUE** [comment]
Which version are you on? These was a bug in one of the releases between 0.0.40 and 0.0.44 which caused this... also, if you are on `master` there was a bug in that also causing this for a separate reason.

**Comment by cfpinto** [comment]
I'm using version 0.0.43 as recommended in installation. I've also activated logging on my .env file

**Comment by REBELinBLUE** [comment]
Oh, I forgot to update the instructions, sorry about that yeah this was fixed in 0.0.44

**Comment by cfpinto** [comment]
OK, will update and check

**Comment by REBELinBLUE** [comment]
Thanks, sorry about that. I've changed the install instructions so it doesn't happen again.

**Comment by cfpinto** [comment]
OK, now it works. I had to do the same as #327 but now it works

**Comment by cfpinto** [comment]
Don't want to open another ticket but I have another question. 

How do I setup a application status url? What is the expected output of the endpoint?

Cheers

**Comment by REBELinBLUE** [comment]
Great. 

I have fixed that issue in master and will be releasing a new version this week

**Comment by REBELinBLUE** [comment]
Simply a URL it calls which doesn't return an error, so anything which returns a 200 status code for instance (200 OK, 201 Created etc). Basically a 40x or 50x code will cause a failure (i.e. 400 Bad Request, 404 Not Found, 500 Internal Server Error)

**Comment by cfpinto** [comment]
ok, is it possible to see the logs of the tests somewhere? I know for a fact the URL is active but I'm still getting an offline warning

**Comment by REBELinBLUE** [comment]
Hmm no actually, but that is a very good idea! I'll add it right now, give me 30 minutes or so

**Comment by cfpinto** [comment]
thanks

**Comment by REBELinBLUE** [comment]
Actually going to take me a bit longer...

However, if you edit app/Jobs/RequestProjectCheckUrl.php and after the line `$link->offline();`

Add

```php
\Illuminate\Support\Facades\Log::error($error->getMessage());
```

then restart the queue listener with `php artisan queue:restart` it will log the message in the log in `storage/logs/`

**Comment by cfpinto** [comment]
Thanks for the hint. It now works

Cheers

**Comment by REBELinBLUE** [comment]
Out of interest what was the problem?

**Comment by cfpinto** [comment]
Just a bad firewall setup. Nothing special. But I couldn't reach the server and without errors it was hard to debug.

**Comment by REBELinBLUE** [comment]
ah

**Comment by cfpinto** [comment]
Yeah I know, I'm embarrassed, sorry
